root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/worker"
  cmd = "go build -o ./tmp/worker ./cmd/worker"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", ".vscode", "logs", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_test\\.go$", "\\.#.*", ".*\\.swp$", ".*\\.tmp$", ".*\\.log$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal", "pkg", "api", "config"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors-worker.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_root = false

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false 